namespace: social-network-explorer

# set tag manually --set image.tag=latest
image:
  repository: socialnetwork/explorer
  tag: 0.71.2
  pullPolicy: IfNotPresent

# if set to true a service account for substrate will be created
rbac:
  enable: true
  name: polkadot-js-apps

# name of deployment
app: social-network-explorer

# base domain
domain: explorer.social.network

replicas: 1

requests:
  cpu: 0.3
  memory: 300Mi
limits:
  cpu: 0.4
  memory: 400Mi

# certificate issuer
production_issuer: true
acme_registration_email: my-email@example.com

k8s_v19_used: false

node_ws_url: wss://tnet.social.network
